swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
      # - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: User get data transactions
      description: API for fetching data user transactions
      produces:
        - application/json
      responses:
        "200":
          description: getting transaction data list Successfully
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transaction/edit/{id}:
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: User update categories
      description: API for update categories for a user transaction by id
      parameters:
        - in: header
          name: Autorization
          description: Bearer token for authentification
          required: true
          type: string
        - in: path
          name: id
          description: Transaction id
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction
          required: true
          schema:
            $ref: "#/definitions/CategoriesTransactions"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction categorie update retrieved successfully
          schema:
            $ref: "#/definitions/UpdateCategoriesResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transaction/delete{id}:
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: User delete note
      description: API for delete a user transaction note by id
      parameters:
        - in: header
          name: Authorization
          description: Bearer token for authentication
          required: true
          type: string
        - in: path
          name: id
          description: Transaction id
          required: true
          type: string

      produces:
        - application/json
      responses:
        "200":
          description: User transaction note delete retrieved successully
          schema:
            $ref: "#/definitions/UpdateResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  TransactionResponse:
    properties:
      Date:
        type: string
        example: "02/02/2024"
      Description:
        type: string
        example: "Golden Sun Bakery"
      Amount:
        type: string
        example: "$8.00"
      Balance:
        type: string
        example: "$298"
      Transaction type:
        type: string
        example: "Electronic"
      Category:
        type: string
        example: "Food"
      Note:
        type: string
        example: "lorem ipsum"
  CategoriesTransactions:
    properties:
      Autorization:
        type: string
        example: "gjizejprg9456rtz4h896t4bg865f4sd564rety89489trsdfgvmklpkporeztkspogkoppkoptrye"
      Id:
        type: string
        example: "12"
  UpdateCategoriesResponse:
    properties:
      Category:
        type: string
        example: "Food"
      Note:
        type: string
        example: "Transaction update success"
  UpdateResponse:
    properties:
      Id:
        type: string
        example: "12"
      note:
        type: string
        example: "note deleted"
